Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Sitegeist.GroundhogDay': ['NodeTypes/*']
      inspector:
        dataTypes:
          'Sitegeist\GroundhogDay\Domain\EventOccurrenceSpecification':
            defaultValue: null
            editor: 'Sitegeist.Groundhogday/Inspector/Editors/OccurenceEditor'
          'DateTimeZone':
            defaultValue: 'UTC'
            editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
    Ui:
      resources:
        javascript:
          '@sitegeist/groundhogday-plugin':
            resource: 'resource://Sitegeist.GroundhogDay/Public/JavaScript/Plugin.js'
